import {chromium} from 'playwright';
const out = process.argv[2];
const browser = await chromium.launch({channel: 'chrome'});
const page = await browser.newPage({viewport: {width: 1400, height: 1000}});
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => {
  if (m.type() === 'error' && !m.text().includes('favicon')) errors.push(m.text());
});
const click = async name => {
  const b = page.getByRole('button', {name, exact: true}).first();
  await b.scrollIntoViewIfNeeded();
  await b.click();
  await page.waitForTimeout(2500);
};
await page.goto('http://localhost:5174/', {waitUntil: 'load'});
await page.waitForTimeout(7000);
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({path: `${out}/01-home.png`});
await click('Documents');
await click('a2ui');
await click('catalogs');
await click('Run search_files');
await page.waitForTimeout(4000);
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({path: `${out}/02-search.png`});
await click('Parent');
await click('Home');
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({path: `${out}/03-home-again.png`});
console.log('errors:', JSON.stringify(errors));
await browser.close();
process.exit(0);
